[package]
name = "monsterbook"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgproc-rs = "0.3.0"
clap = { git = "https://github.com/clap-rs/clap/", features = ["derive"] }
